---
apiVersion: v1
kind: Service
metadata:
  name: customer
  labels:
    app: customer
spec:
  type: NodePort
  selector:
    app: customer
  ports:
  - protocol: TCP
    port: 8080
    name: http
    nodePort: 31000

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: customer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
      - name: customer
        image: nidhi999/customer_img
        ports:
        - containerPort: 8080
          

        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8080
        #   initialDelaySeconds: 30
        #   timeoutSeconds: 1