---
apiVersion: v1
kind: Service
metadata:
  name: delivery
  labels:
    app: delivery
spec:
  type: NodePort
  selector:
    app: delivery
  ports:
  - protocol: TCP
    port: 8080
    name: http
    nodePort: 31001

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: delivery
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: delivery
    spec:
      containers:
      - name: delivery
        image: nidhi999/delivery_img
        ports:
        - containerPort: 8080
          

        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8080
        #   initialDelaySeconds: 30
        #   timeoutSeconds: 1