---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 5173
    name: http
    nodePort: 31006

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: nidhi999/frontend_img
        ports:
        - containerPort: 5173
          

        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 5127
        #   initialDelaySeconds: 30
        #   timeoutSeconds: 1