---
apiVersion: v1
kind: Service
metadata:
  name: management
  labels:
    app: management
spec:
  type: NodePort
  selector:
    app: management
  ports:
  - protocol: TCP
    port: 8080
    name: http
    nodePort: 31002

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: management
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: management
    spec:
      containers:
      - name: management
        image: nidhi999/management_img
        ports:
        - containerPort: 8080
          

        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8080
        #   initialDelaySeconds: 30
        #   timeoutSeconds: 1