apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  nginx.conf: |
    http {
        include /etc/nginx/mime.types;
        types {
            application/javascript   js mjs;
            text/css                 css;
            # Add more MIME types as needed
        }
    }
