---
apiVersion: v1
kind: Service
metadata:
  name: ordering
  labels:
    app: ordering
spec:
  type: NodePort
  selector:
    app: ordering
  ports:
  - protocol: TCP
    port: 8080
    name: http
    nodePort: 31004

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: ordering
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ordering
    spec:
      containers:
      - name: ordering
        image: nidhi999/ordering_img
        ports:
        - containerPort: 8080
          

        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8080
        #   initialDelaySeconds: 30
        #   timeoutSeconds: 1