---
apiVersion: v1
kind: Service
metadata:
  name: preparation
  labels:
    app: preparation
spec:
  type: NodePort
  selector:
    app: preparation
  ports:
  - protocol: TCP
    port: 8080
    name: http
    nodePort: 31003

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: preparation
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: preparation
    spec:
      containers:
      - name: preparation
        image: nidhi999/preparation_img
        ports:
        - containerPort: 8080
          

        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8080
        #   initialDelaySeconds: 30
        #   timeoutSeconds: 1